name: Build and deploy Python app to Azure Web App

concurrency:
  group: deploy-tech0-gen-11-step3-2-py-52
  cancel-in-progress: true

on:
  push:
    branches:
      - master   # ← masterでなければ main に
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'


      # GitHub Actions側でライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages"


      # ⚠️ Azure(Oryx)でビルドするので、ここでvenvは作らない
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tech0-gen-11-step3-2-py-52
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A7628BD7C8E34F13AD12830EEC0CE8FB }}
          package: .
          clean: true
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: false